name: Back end CI-CD test

on:
  pull_request:
  push:
    branches: [main,develop]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
            
      - name: Build with Maven
        run: mvn clean verify
        working-directory: ./back
        
      - name: Generate JaCoCo report
        run: mvn jacoco:report
        working-directory: ./back
        
      - name: Upload Jacoco report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-code-coverage-report
          path: back/target/site/jacoco
    
