name: CD

on:
  pull_request:
  push:
    branches: [main, develop]
    
jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker images
        run: |
          docker build -t bobapp-backend ./back
          docker build -t bobapp-frontend ./front
          
      - name: Push Docker images
        run: |
          docker tag bobapp-backend ${{ vars.DOCKER_USERNAME }}/bobapp-backend:latest
          docker tag bobapp-frontend ${{ vars.DOCKER_USERNAME }}/bobapp-frontend:latest
          docker push ${{ vars.DOCKER_USERNAME }}/bobapp-backend:latest
          docker push ${{ vars.DOCKER_USERNAME }}/bobapp-frontend:latest
